# Generated by Django 5.2.8 on 2026-01-15 03:58

import dagu.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, verbose_name='모델명')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('category', models.CharField(choices=[('guitar', '기타'), ('bass', '베이스'), ('keyboard', '키보드/신디'), ('drum', '드럼/퍼커션'), ('effect', '이펙터'), ('amp', '앰프'), ('acoustic', '어쿠스틱'), ('other', '기타 악기')], default='guitar', max_length=50, verbose_name='카테고리')),
                ('image_url', models.URLField(blank=True, verbose_name='대표 이미지 URL')),
                ('reference_price', models.PositiveIntegerField(default=0, help_text='신품 정가 (원)', verbose_name='신품 기준가')),
                ('description', models.TextField(blank=True, verbose_name='설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '악기',
                'verbose_name_plural': '악기 목록',
                'ordering': ['brand', 'name'],
                'indexes': [models.Index(fields=['brand'], name='dagu_instru_brand_9bf97b_idx'), models.Index(fields=['category'], name='dagu_instru_categor_0dc989_idx'), models.Index(fields=['name'], name='dagu_instru_name_1f8469_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('price', models.PositiveIntegerField(verbose_name='판매가')),
                ('link', models.URLField(verbose_name='판매 링크')),
                ('source', models.CharField(choices=[('bunjang', '번개장터'), ('joonggonara', '중고나라'), ('danggn', '당근마켓'), ('other', '기타')], default='other', max_length=50, verbose_name='출처')),
                ('title', models.CharField(blank=True, max_length=300, verbose_name='매물 제목')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성 상태')),
                ('expired_at', models.DateTimeField(db_index=True, default=dagu.models.default_expiry, verbose_name='만료 시간')),
                ('click_count', models.PositiveIntegerField(default=0, verbose_name='클릭 수')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instrument', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_items', to='dagu.instrument', verbose_name='악기')),
            ],
            options={
                'verbose_name': '중고 매물',
                'verbose_name_plural': '중고 매물 목록',
                'ordering': ['price', '-created_at'],
                'indexes': [models.Index(fields=['is_active', 'expired_at'], name='dagu_userit_is_acti_d17b95_idx'), models.Index(fields=['price'], name='dagu_userit_price_56eff5_idx')],
            },
        ),
    ]
