# Generated by Django 5.2.8 on 2026-01-15 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='image_url',
            field=models.URLField(blank=True, max_length=2000, verbose_name='대표 이미지 URL'),
        ),
        migrations.AlterField(
            model_name='instrument',
            name='name',
            field=models.CharField(max_length=500, verbose_name='모델명'),
        ),
        migrations.AlterField(
            model_name='useritem',
            name='link',
            field=models.URLField(max_length=2000, verbose_name='판매 링크'),
        ),
    ]
