# Generated by Django 5.2.8 on 2026-01-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0002_alter_instrument_image_url_alter_instrument_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useritem',
            name='source',
            field=models.CharField(choices=[('bunjang', '번개장터'), ('joonggonara', '중고나라'), ('danggn', '당근마켓'), ('mule', '뮬'), ('other', '기타')], default='other', max_length=50, verbose_name='출처'),
        ),
    ]
