# Generated by Django 5.2.8 on 2026-01-16 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0003_alter_useritem_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='extended_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='연장 시점'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='owner_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='등록자 ID'),
        ),
    ]
