# Generated by Django 5.2.8 on 2026-01-16 14:55

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0004_useritem_extended_at_useritem_owner_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useritem',
            name='is_under_review',
            field=models.BooleanField(default=False, verbose_name='검토 중'),
        ),
        migrations.AddField(
            model_name='useritem',
            name='report_count',
            field=models.PositiveIntegerField(default=0, verbose_name='신고 횟수'),
        ),
        migrations.CreateModel(
            name='ItemReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reporter_id', models.IntegerField(db_index=True, verbose_name='신고자 ID')),
                ('reason', models.CharField(choices=[('wrong_price', '가격이 다릅니다'), ('sold_out', '이미 판매완료된 매물입니다'), ('fake', '허위/사기 매물입니다'), ('inappropriate', '부적절한 내용입니다'), ('other', '기타')], default='other', max_length=50, verbose_name='신고 사유')),
                ('detail', models.TextField(blank=True, verbose_name='상세 내용')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='dagu.useritem', verbose_name='매물')),
            ],
            options={
                'verbose_name': '매물 신고',
                'verbose_name_plural': '매물 신고 목록',
                'ordering': ['-created_at'],
                'unique_together': {('item', 'reporter_id')},
            },
        ),
    ]
