# Generated by Django 5.2.8 on 2026-01-16 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0005_add_report_fields'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='itemreport',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='itemreport',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='세션 키'),
        ),
        migrations.AlterField(
            model_name='itemreport',
            name='reporter_id',
            field=models.IntegerField(blank=True, db_index=True, null=True, verbose_name='신고자 ID'),
        ),
    ]
