# Generated by Django 5.2.8 on 2026-01-17 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0006_allow_anonymous_reports'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200, verbose_name='검색어')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='검색 횟수')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='마지막 검색')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '검색어',
                'verbose_name_plural': '검색어 목록',
                'ordering': ['-search_count', '-last_searched_at'],
            },
        ),
    ]
