# Generated by Django 5.2.8 on 2026-01-18 02:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0007_add_search_query'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemClick',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clicked_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clicks', to='dagu.useritem', verbose_name='매물')),
            ],
            options={
                'verbose_name': '클릭 로그',
                'verbose_name_plural': '클릭 로그 목록',
                'indexes': [models.Index(fields=['clicked_at'], name='dagu_itemcl_clicked_9c4c75_idx')],
            },
        ),
    ]
