# Generated by Django 5.2.8 on 2026-01-18 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0008_itemclick'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instrument',
            name='category',
            field=models.CharField(choices=[('guitar', '기타'), ('bass', '베이스'), ('keyboard', '키보드/신디'), ('drum', '드럼/퍼커션'), ('effect', '이펙터'), ('amp', '앰프'), ('acoustic', '어쿠스틱'), ('mic', '마이크'), ('other', '기타 악기')], default='guitar', max_length=50, verbose_name='카테고리'),
        ),
    ]
