# Generated by Django 5.2.8 on 2026-01-18 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0009_alter_instrument_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchMissLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(db_index=True, max_length=200, verbose_name='검색어')),
                ('normalized_query', models.CharField(db_index=True, help_text='소문자, 공백 정리된 검색어', max_length=200, verbose_name='정규화된 검색어')),
                ('search_count', models.PositiveIntegerField(default=1, verbose_name='검색 횟수')),
                ('last_searched_at', models.DateTimeField(auto_now=True, verbose_name='마지막 검색')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_resolved', models.BooleanField(default=False, verbose_name='처리 완료')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='처리 시점')),
                ('resolved_instrument', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_misses', to='dagu.instrument', verbose_name='등록된 악기')),
            ],
            options={
                'verbose_name': '미등록 검색어',
                'verbose_name_plural': '미등록 검색어 목록',
                'ordering': ['-search_count', '-last_searched_at'],
            },
        ),
    ]
