# Generated by Django 5.2.8 on 2026-01-19 09:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0010_searchmisslog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='브랜드명 (정식)')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL 슬러그')),
                ('logo_url', models.URLField(blank=True, max_length=2000, verbose_name='로고 URL')),
                ('description', models.TextField(blank=True, verbose_name='브랜드 설명')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '브랜드',
                'verbose_name_plural': '브랜드 목록',
                'ordering': ['name'],
            },
        ),
        migrations.AlterField(
            model_name='instrument',
            name='brand',
            field=models.CharField(max_length=100, verbose_name='브랜드 (Legacy)'),
        ),
        migrations.AddField(
            model_name='instrument',
            name='brand_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='instruments', to='dagu.brand', verbose_name='브랜드 (Relation)'),
        ),
    ]
