# Generated by Django 5.2.8 on 2026-01-21 04:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dagu', '0011_brand_alter_instrument_brand_instrument_brand_obj'),
    ]

    operations = [
        migrations.AddField(
            model_name='instrument',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='dagu.instrument', verbose_name='상위 악기 (부모)'),
        ),
    ]
